# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\tDNNServer\"|\n\x05Query\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08model_id\x18\x02 \x01(\x05\x12\n\n\x02\x62s\x18\x03 \x01(\x05\x12\x0f\n\x07seq_len\x18\x04 \x01(\x05\x12\x13\n\x0bstart_stamp\x18\x05 \x01(\x01\x12\x12\n\nqos_target\x18\x06 \x01(\x05\x12\x0f\n\x07load_id\x18\x07 \x01(\x05\"<\n\x06Result\x12\x0f\n\x07node_id\x18\x01 \x01(\x05\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x02 \x01(\x08\x12\x0f\n\x07\x65lapsed\x18\x03 \x01(\x01\x32=\n\tDNNServer\x12\x30\n\tInference\x12\x10.DNNServer.Query\x1a\x11.DNNServer.Resultb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _QUERY._serialized_start=28
  _QUERY._serialized_end=152
  _RESULT._serialized_start=154
  _RESULT._serialized_end=214
  _DNNSERVER._serialized_start=216
  _DNNSERVER._serialized_end=277
# @@protoc_insertion_point(module_scope)
